"""points table

Revision ID: 8065ac6913cc
Revises: 
Create Date: 2020-04-18 21:38:04.114142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8065ac6913cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('happy', sa.Integer(), nullable=True),
    sa.Column('sad', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_timestamp'), 'point', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_timestamp'), table_name='point')
    op.drop_table('point')
    # ### end Alembic commands ###
